### ISSUE TITLE
Serial server input/output error 

### ISSUE THREAD

**Issue by TheMotonaut** [ETAChalmers/Kallebol_elevation#2]
Sending results in Input/output error on serial server on Kallebol

`ERROR:root:[Errno 5] Input/output error`

restarting the server results in:

`ERROR:root:Could not open serial port /dev/ttyACM0: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'`

 This caused by the device switching port from ttyACM0 to ttyACM1. Occasionally it switches back to ACM0.

**Comment by TheMotonaut** [comment]
Using screen kicks user out when sending data. Likely caused by the same error

**Comment by ertex** [comment]
skill issue

**Comment by mateuszdrwal** [comment]
> This caused by the device switching port from ttyACM0 to ttyACM1. Occasionally it switches back to ACM0.

Use /dev/serial instead, that way you won't be jumpscared by the device switching serial ports
